# Generated by Django 5.0.6 on 2024-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField()),
                ('telefone', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('endereco', models.TextField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
                ('email', models.TextField()),
                ('modalidade', models.TextField()),
                ('horario', models.TextField()),
            ],
        ),
    ]
