# Generated by Django 5.0.6 on 2024-05-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
