# Generated by Django 5.0.6 on 2024-05-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_alunos', '0002_rename_alunos_aluno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Alunocad',
        ),
    ]
